// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHuczwHQXwZMu421TILuAHNyGkipns_Nw',
    appId: '1:9174506984:web:b8602073864f38ae0a185d',
    messagingSenderId: '9174506984',
    projectId: 'test5-chap4-fb-ov',
    authDomain: 'test5-chap4-fb-ov.firebaseapp.com',
    storageBucket: 'test5-chap4-fb-ov.appspot.com',
    measurementId: 'G-EMZV7VCRVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg5hTFzn-w7rj2EdQwhFSeqJlk_q_E-CA',
    appId: '1:9174506984:android:dd792cc9fae783ac0a185d',
    messagingSenderId: '9174506984',
    projectId: 'test5-chap4-fb-ov',
    storageBucket: 'test5-chap4-fb-ov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChM5DNziAQu2cggL4glliGZQUci5VnsA0',
    appId: '1:9174506984:ios:8f690ec4b36eb1fb0a185d',
    messagingSenderId: '9174506984',
    projectId: 'test5-chap4-fb-ov',
    storageBucket: 'test5-chap4-fb-ov.appspot.com',
    iosClientId: '9174506984-6nkpnt0uambfkaumkenvotnk0p967v4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.test5Chap4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChM5DNziAQu2cggL4glliGZQUci5VnsA0',
    appId: '1:9174506984:ios:8f690ec4b36eb1fb0a185d',
    messagingSenderId: '9174506984',
    projectId: 'test5-chap4-fb-ov',
    storageBucket: 'test5-chap4-fb-ov.appspot.com',
    iosClientId: '9174506984-6nkpnt0uambfkaumkenvotnk0p967v4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.test5Chap4',
  );
}
